version: '2.2'

services:
    ceph-base:
        volumes:
            - ./docker/ceph:/docker:ro
        environment:
            - ALERTMANAGER_HOST_PORT=${ALERTMANAGER_HOST_PORT}
            - CEPH_DEBUG=${CEPH_DEBUG:-0}
            - CEPH_PORT=10000
            - DASHBOARD_DEV_SERVER=${DASHBOARD_DEV_SERVER:-1}
            - FS
            - GANESHA
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
            - MDS
            - MGR
            - MON
            - NG_CLI_ANALYTICS=false
            - NODE_EXPORTER_HOST_PORT=${NODE_EXPORTER_HOST_PORT}
            - OSD
            - PROMETHEUS_HOST_PORT=${PROMETHEUS_HOST_PORT}
            - PYTHONDONTWRITEBYTECODE=1
            - REMOTE_DASHBOARD_URL
            - RGW
            - RGW_MULTISITE=${RGW_MULTISITE:-0}
        command: /docker/start.sh
        scale: -1

    ceph-build-base:
        extends:
            service: ceph-base
        image: rhcsdashboard/ceph:${CEPH_IMAGE_TAG:-master}
        volumes:
            - ${HOST_CCACHE_DIR}:/root/.ccache
            - ${CEPH_REPO_DIR}:/ceph
            - ${CEPH_CUSTOM_BUILD_DIR:-empty_volume}:/build
        environment:
            - BUILD_DATE=1981-05-09
            - CEPH_ASOK_DIR=/ceph/build/ceph/out
            - CEPH_BIN=/ceph/build/bin
            - CEPH_CONF=/ceph/build/ceph/ceph.conf
            - CEPH_CONF_PATH=/ceph/build/ceph
            - CEPH_DEV_DIR=/ceph/build/ceph/dev
            - CEPH_OUT_DIR=/ceph/build/ceph/out
            - CHECK_MYPY=${CHECK_MYPY:-0}
            - DASHBOARD_SSL=${DASHBOARD_SSL:-1}
            - SOURCE_DATE_EPOCH=358228200
        cap_add:
            - ALL
        entrypoint: /docker/entrypoint.sh

    ceph-rpm-base:
        extends:
            service: ceph-base
        image: ${CEPH_RPM_IMAGE:-rhcsdashboard/ceph-rpm:centos7}
        volumes:
            - ${CEPH_RPM_REPO_DIR:-empty_volume}:/ceph
            - /ceph/build
        environment:
            - CEPH_ASOK_DIR=/ceph/build.ceph-rpm/out
            - CEPH_BIN=/usr/bin
            - CEPH_CONF=/ceph/build.ceph-rpm/ceph.conf
            - CEPH_CONF_PATH=/ceph/build.ceph-rpm
            - CEPH_DEV_DIR=/ceph/build.ceph-rpm/dev
            - CEPH_LIB=/usr/lib64/ceph
            - CEPH_OUT_DIR=/ceph/build.ceph-rpm/out
            - CEPH_RPM_REPO_DIR
            - DASHBOARD_SSL=${DASHBOARD_SSL:-0}
        entrypoint: /docker/rpm/entrypoint.sh
