version: '2.2'

services:
    ceph-base:
        volumes:
            - ./docker/ceph:/docker:ro
        environment:
            - ALERTMANAGER_HOST_PORT=${ALERTMANAGER_HOST_PORT}
            - CEPH_PORT=10000
            - GRAFANA_HOST_PORT=${GRAFANA_HOST_PORT}
            - PYTHONDONTWRITEBYTECODE=1
            - RGW_MULTISITE=${RGW_MULTISITE:-0}
        mem_limit: 3g

    ceph-build-base:
        extends:
            service: ceph-base
        image: rhcsdashboard/ceph:${CEPH_IMAGE_TAG:-fedora29}
        volumes:
            - ${HOST_CCACHE_DIR}:/root/.ccache
            - ${CEPH_REPO_DIR}:/ceph
            - ${CEPH_CUSTOM_BUILD_DIR:-empty_volume}:/build
        environment:
            - BUILD_DATE=1981-05-09
            - CEPH_ASOK_DIR=/ceph/build/ceph/out
            - CEPH_BIN=/ceph/build/bin
            - CEPH_CONF=/ceph/build/ceph/ceph.conf
            - CEPH_CONF_PATH=/ceph/build/ceph
            - CEPH_DEV_DIR=/ceph/build/ceph/dev
            - CEPH_OUT_DIR=/ceph/build/ceph/out
            - DASHBOARD_SSL=${DASHBOARD_SSL:-1}
            - MDS
            - MGR
            - MON
            - OSD
            - RGW
            - SOURCE_DATE_EPOCH=358228200
        cap_add:
            - ALL
        entrypoint: /docker/entrypoint.sh
        command: /docker/start.sh

    ceph-rpm-base:
        extends:
            service: ceph-base
        image: ${CEPH_RPM_IMAGE:-rhcsdashboard/nautilus:v14.2.0}
        volumes:
            - ${CEPH_RPM_REPO_DIR:-empty_volume}:/ceph/dev
        environment:
            - CEPH_ASOK_DIR=/ceph/dev/build/ceph-rpm/out
            - CEPH_BIN=/usr/bin
            - CEPH_CONF=/ceph/dev/build/ceph-rpm/ceph.conf
            - CEPH_CONF_PATH=/ceph/dev/build/ceph-rpm
            - CEPH_DEV_DIR=/ceph/dev/build/ceph-rpm/dev
            - CEPH_OUT_DIR=/ceph/dev/build/ceph-rpm/out
            - CEPH_RPM_DEV=${CEPH_RPM_DEV:-false}
            - CEPH_RPM_DEV_DIR=/ceph/dev
            - DASHBOARD_SSL=${DASHBOARD_SSL:-0}
        entrypoint: /docker/rpm/entrypoint.sh
        command: /docker/rpm/start.sh
        scale: -1
