[
    {
        "targets": [ "ceph:9283" ],
        "labels": {}
    },
    {
        "targets": [ "ceph2:9283" ],
        "labels": {}
    },
    {
        "targets": [ "ceph-rpm:9283" ],
        "labels": {}
    },
    {
        "targets": [ "ceph-rpm2:9283" ],
        "labels": {}
    }
]