apiVersion: 1

deleteDatasources:
  - name: Dashboard1
    orgId: 1

datasources:
  - name: Dashboard1
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    editable: true
